### PR TITLE
Feature/larpandoracontent_v03_15_16

### PR DESCRIPTION
**Pull request by PandoraPFA**
Hi, This is a set of related features that have converged ready for a new development push for two-view LArTPCs (so e.g. ProtoDUNE-DP or recovery mode for a single-phase LArTPC). The changelog snippet, with links to individual pull requests on PandoraPFA/LArContent are linked here. No change in behaviour is expected, with these features enabling new developments.

> Restructured 2D->3D matching algorithms in order to support two-view matching approaches.
[PR #107](https://github.com/PandoraPFA/LArContent/pull/107)

> Further restructuring of 2D->3D matching for optimal sharing of code between two-view and three-view cases.
[PR #112](https://github.com/PandoraPFA/LArContent/pull/112)

> Added option to fold/unfold mc particle hierarchies in event validation processes.
[PR #110](https://github.com/PandoraPFA/LArContent/pull/110)

> Allowed validation algorithms to read all primary selection parameters from xml.
[PR #108](https://github.com/PandoraPFA/LArContent/pull/108)

> Templated PfoCharacterisation algorithm on mva type.
[PR #109](https://github.com/PandoraPFA/LArContent/pull/109)

> Tidied up contents of pfo info map when adjusting vertex.
[Commit](https://github.com/PandoraPFA/LArContent/commit/2cd6434)

> Handled variable that was unused only in case when building with monitoring off.
[Commit](https://github.com/PandoraPFA/LArContent/commit/5974959)

@vitodb kindly made available the ability to trigger CI off branches of the PandoraPFA/LArContent repo, and Christoph kindly triggered the DUNE tests today, see successful results [here](https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/8459&platform=Linux%203.10.0-1062.12.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof).

Major changes related to PR#107 and PR#112, with overall N-view cluster matching structures as described in the following:
Screenshot 2020-03-30 at 17 13 51

As ever, please don't hesitate to get in touch if there's any issues or anything needing further discussion. Thanks!

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by johnmarshall80** [comment]
Hi, I don't really understand the test result outputs. There doesn't seem to be anything related to reconstruction, and almost certainly nothing to do with the features in this PR, but there are changes, e.g. for uBooNE, changes emerge in the G4 step (which then propagate through detsim and reco), so presumably other changes have been included in the mix? Thanks for any insights!

**Comment by lgarren** [comment]
@johnmarshall80 Are you referring to warnings in the CI tests?  Those are normal.

**Comment by johnmarshall80** [comment]
Hi @lgarren - Yes, the warnings are apparently due to changes in output product sizes, many/mostly (in this case) for products running prior to the reconstruction. I had assumed these would remain unchanged unless there was more going on in this test than just introducing the features in this pull request (such as other code changes, or different seeds in a generator or G4 process, etc.). I really like the way the CI setup is embedded in our new GitHub PR procedures, and was just trying to get my head around what the test outputs were telling us. I can't see any change related to this feature, which is what I'd hope/expect. Thanks!

**Comment by lgarren** [comment]
@tomjunk  @hgreenlee  Would one of you please approve this PR?

**Comment by tomjunk** [comment]
approved

This test looks good, the one Christoph launched and Vito enabled.   Lots of commits, but it's not supposed to do anything different (yet), and looks like it didn't.

https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/8459&platform=Linux%203.10.0-1062.12.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof

**Comment by lgarren** [comment]
approve

**Pull request merged**
