### PR TITLE
Feature/larpandoracontent v03 22 04

### PR DESCRIPTION
**Pull request by echardon**
In this PR we create a new member variable `m_daughterVolumeId` in the LArCaloHit class such that we know the daughter volume ID of each hit. There is now 1 daughter volume per CRP (see associated LArPandora PR). This ensures that 2D clusters coming from different CRPs can't be matched together. This check is now performed in the view-matching algorithms and works as follows: we look at the intersection between the list of daughter volumes of each cluster, if the intersection is empty the match cannot happen.

To avoid compatibility issues with older reconstructed data we introduce a new XML parameter in the LArMaster block. One needs to have `<LArCaloHitVersion>2</LArCaloHitVersion>` to enable this functionality. If it does not appear in the file, the behaviour is left unchanged.

This PR is related to LArPandora PR https://github.com/LArSoft/larpandora/pull/15 , which reads in the daughter volumes.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by absolution1** [comment]
I just need to confirm with the DUNE CI manager that the product differences are OK here.

**Comment by absolution1** [comment]
It's fine.  Approving now.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
