### PR TITLE
larpandoracontent v04_08_00

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR for larpandoracontent version v04_08_00 contains updates to support graph building to produce inputs for GNNs and Transformers. This will not alter the products for any experiment.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@AndyChappell The build is failing to find an eigen header.  The edit below resolves the problem.  Note that legacy variable `EIGEN3_INCLUDE_DIRS` is no longer defined.  
```
diff --git a/larpandoradlcontent/CMakeLists.txt b/larpandoradlcontent/CMakeLists.txt
index 0ed7430d..937322d9 100644
--- a/larpandoradlcontent/CMakeLists.txt
+++ b/larpandoradlcontent/CMakeLists.txt
@@ -11,6 +11,8 @@ cet_make_library(LIBRARY_NAME ${LAR_DL_CONTENT_LIBRARY_NAME}
   ${LAR_CONTENT_LIBRARY_NAME}
   PandoraPFA::PandoraSDK
   torch
+  PRIVATE
+  Eigen3::Eigen
 )
```

**Comment by AndyChappell** [comment]
Thanks Lynn, that should be fixed.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Pull request merged**
