### PR TITLE
Feature/larpandoracontent_v03_15_14

### PR DESCRIPTION
**Pull request by PandoraPFA**
On behalf of @echardon, and based off commits reviewed as part of this PandoraPFA [PR](https://github.com/PandoraPFA/LArContent/pull/103).

Comments, from Etienne (_note especially_ the accompanying "feature/echardon" branch for dunetpc, on Redmine):

> Added IsDualPhase as a boolean parameter in LArCosmicRayVertexBuilding algorithm so that a cosmic ray vertex is the hit with highest-x. True by default only in *DP.xml files that will be included after the merging of feature/echardon to dunetpc (v08_41_00)

Many thanks!

### CODE REVIEW

**Comment by gartung** [comment]
trigger build

**Comment by gartung** [comment]
All of the experiment CI failures are because the larsoft build tarball cannot be downloaded.

**Comment by lgarren** [comment]
About half of the CI tests ran.  Enough to see that this is not a breaking change.  The supplied feature branch for dunetpc merely enables use of the new options.

**Comment by lgarren** [comment]
approve

**Pull request merged**
