### PR TITLE
Feature/larpandoracontent v04 07 00

### PR DESCRIPTION
**Pull request by knoepfel**
Includes changes from #60, plus application of `format-code`.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by AndyChappell** [comment]
> Includes changes from #60, plus application of `format-code`.

Thanks Kyle.

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@AndyChappell Would you take a look at the uboone CI failure?  It's not clear if the problem is related to this PR.

**Comment by lgarren** [comment]
icarus tests tests warning on slf7 for e26:prof
https://dbweb8.fnal.gov:8443/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9125&builds=

**Comment by AndyChappell** [comment]
@lgarren This appears to be a problem at the generator stage with a missing registry key NGenerators, so this is unrelated to this PR.

**Comment by lgarren** [comment]
Thanks @AndyChappell

**Comment by lgarren** [comment]
approve

**Pull request merged**
