### PR TITLE
feature/larpandoracontent_v03_16_01

### PR DESCRIPTION
**Pull request by AndyChappell**
Hi, this PR includes features to support the selection of slices based on user-defined criteria, as well as some minor modifications to boolean manipulation to conform to the -Wint-in-bool-context flag. The PR breakdown is as follows:

- Slice selection support added in [PandoraPFA#121](https://github.com/PandoraPFA/LArContent/pull/121) and [PandoraPFA#123](https://github.com/PandoraPFA/LArContent/pull/123)
- Minor modification to boolean handling in [PandoraPFA#120](https://github.com/PandoraPFA/LArContent/pull/120)

The slice selection updates are intended to support training set generation and as such are not part of the standard configuration, so no changes are expected and no experiment code/config changes are necessary.

We've triggered the CI off the relevant branches of the PandoraPFA/LArContent and dunetpc repositories. All tests passed, and the result can be found [here](https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/9285&platform=Linux%203.10.0-1127.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof).

Please do not hesitate to get in touch if further information is required.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by aihimmel** [comment]
If the CI tests pass (will someone check?), and this is not intended to change any behavior in use by the experiments, I think this is fine to go in.

**Comment by lgarren** [comment]
CI tests are mostly OK.  There are problems unrelated to this PR.

**Comment by tomjunk** [comment]
I looked at the CI results for DUNE's reco integration tests and they all line up as unchanged, using the link Andy provided above.

https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/9285&platform=Linux%203.10.0-1127.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof

I'm okay to proceed with this, though I cannot tell if the new features work as desired.

**Comment by lgarren** [comment]
approve

**Pull request merged**
