### PR TITLE
feature/larpandoracontent_v04_03_03

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR for larpandoracontent version v04_03_03 updates feature map handling for the TrackShowerIdFeatureTool to directly pass InitializedDoubles rather than primitive doubles, preventing an exception being thrown in the event of an uninitialized feature.

This update may alter product outputs where uninitialized features were present previously (on the order of one PFP in every 400 events).

### CODE REVIEW

**Comment by lgarren** [comment]
@AndyChappell are you able to apply our clang format?  The code checks failed.  https://github.com/LArSoft/larpandoracontent/pull/52#issuecomment-1485423577

**Comment by AndyChappell** [comment]
> @AndyChappell are you able to apply our clang format?

Done. Not quite sure what happened the first time I tried to do that.

**Comment by lgarren** [comment]
Thanks @AndyChappell  We had some problems on our end that are now resolved.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Pull request merged**
