### PR TITLE
feature/larpandoracontent_v03_22_03

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR contains a new algorithm designed to refine showers by feeding the result of the PFO track/shower classification into the shower growing stage of the reconstruction and iterating the process until no more changes are made or a maximum number of iterations is reached.

In addition, this PR also includes a minor CMakeLists.txt update to silence the warnings generated by the LibTorch headers.

As this PR does not activate this algorithm, or change any existing algorithms, no product changes are expected.

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
Oops.  Looks like we're still waiting on some experiments to update their product_deps.  I guess we'll need to relaunch the CI once that work has been completed.

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
The DUNE error is unrelated and has been going on for a few days.
SBND looks good.
uboonecode has few warnings for all stages.  There are some pandora-related product differences in their reco2, but they are accompanied by a lot of unrelated product changes, so it's difficult to know if this change has had an impact.  Given that DUNE/SBND don't have the same kinds of warnings I'm going to assume this is unrelated...

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
