### PR TITLE
feature/larpandoracontent_v03_22_06

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR adds the capability to make use of PandoraMonitoring API functionality added in a previous SDK update for saving events and also updates the Makefile-based build available for standalone instances of Pandora (the build for LArSoft is unchanged).

These changes will not alter product outputs for any experiment.

### CODE REVIEW

**Comment by lgarren** [comment]
@AndyChappell  We seem to have crossed paths on this one.  We just tagged larpandoracontent v03_22_05 with updates needed for art 3.06.  Please merge the head of develop with this PR.  Thanks

**Comment by AndyChappell** [comment]
> @AndyChappell We seem to have crossed paths on this one. We just tagged larpandoracontent v03_22_05 with updates needed for art 3.06. Please merge the head of develop with this PR. Thanks

No problem, I'll merge and adjust this one to v03_22_06.

**Comment by AndyChappell** [comment]
> No problem, I'll merge and adjust this one to v03_22_06.

Done.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests are OK.  ICARUS hasn't updated yet and the DUNE CI failures are unrelated to this PR.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
