### PR TITLE
feature/larpandoracontent_v03_22_01

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR contains a number of updates designed to improve the robustness of the track/shower characterisation feature added in larpandoracontent v03_20_00 and patched in larpandoracontent v03_21_01.

A minor dunetpc update is associated with this PR (feature/chappell_pdsp_ts_update) - a separate redmine issue will be created for this.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by absolution1** [comment]
It looks like all of the 'failures' in the CI are unrelated to this PR.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
running the CI tests again now that the uboone suite has been updated

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
CI tests are normal

**Comment by lgarren** [comment]
approve

**Comment by absolution1** [comment]
Hi @lgarren 
How come this hasn't been merged?  It looks like there's the prerequisite L1/L2 approval?

**Comment by lgarren** [comment]
@absolution1  Some PR's are merged when the release is tagged.  We do that with all larpandoracontent PR's because there are extra considerations.

**Pull request merged**
