### PR TITLE
Add Pandora style clang-format

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR adds a .clang-format file for the Pandora coding style.

### CODE REVIEW

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
@AndyChappell  There is a whitespace issue.  Probably snuck in because the code checks were not working properly until we fixed them a month or so ago.

**Comment by AndyChappell** [comment]
@lgarren That should now be addressed.

**Comment by lgarren** [comment]
thanks @AndyChappell - testing the new code check script now

**Pull request merged**
