### PR TITLE
Feature/larpandoracontent v03 21 00

### PR DESCRIPTION
**Pull request by imawby**
Hello, 

This PR replaces the TrackInEMShower algorithm with the TrackMergeRefinement algorithm within Pandora. This PR accompanies the PR of the imawby_dunefdCosmicRayRecoModule branch to dunetpc (https://cdcvs.fnal.gov/redmine/projects/dunetpc/repository/show/fcl?rev=feature%2Fimawby_dunefdCosmicRayRecoModule). **It is important to mention that these PRs must be merged at the same time as this larpandoracontent PR removes some features that dunetpc depends on (this dependency is removed in the dunetpc PR referenced).**

The TrackMergeRefinement algorithm (previously the TrackInEMShower algorithm) is a 2D hit clustering algorithm that attempts to better cluster cosmic ray muon tracks that have been split by large amounts of electromagnetic behaviour. In terms of code structure, the TrackInEMShower algorithm has been refactored into the TrackMergeRefinement algorithm which inherits from a newly created TrackRefinementBase algorithm. In terms of functionality, the TrackMergeRefinement algorithm primarily improves upon the TrackInEMShower algorithm by including a consideration of the detector gaps when searching for split muon tracks. This is essential to optimise the algorithm's performance when removing the stitching procedure in the DUNE FD cosmic ray reconstruction which will be implemented in the accompanying dunetpc branch. 

Our internal PR to the PandoraPFA/LArContent repository is given here (PandoraPFA#139).

I have triggered the CI off the relevant branches of the PandoraPFA/LArContent and dunetpc repositories. The result shows no warnings or errors and can be found here (https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/10332&platform=Linux%203.10.0-1127.18.2.el7.x86_64&phase=build&buildtype=slf7%20e19:prof).   Please do not hesitate to get in touch if further information is required, i'm happy to help 😄

### CODE REVIEW

**Comment by absolution1** [comment]
@chalt007 will probably know more but my guess is that only the neutrino reco is tested in dunetpc.
We should also check how this impacts the other experiments so I'll trigger the CI now and we can see what happens.

**Comment by absolution1** [comment]
trigger build

**Comment by chalt007** [comment]
Yes, we only run one electron-neutrino event in the CI test. We also run weekly validation builds with a large number of neutrino events (both electron and muon neutrinos). 
@imawby Is this feature only used in the DUNE FD reco? And is it only applied to cosmic ray muons, i.e. down-going muons? Otherwise we could see an effect in the validation builds or in the protoDUNE reco.

**Comment by imawby** [comment]
@chalt007 this is only used in the dune fd reconstruction and is only applied to cosmic ray muons.

**Comment by chalt007** [comment]
Okay, then it probably won't show up in any of the DUNE CI tests or validation builds.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Pull request merged**
