### PR TITLE
feature/larpandoracontent_v04_09_00

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR for larpandoracontent version v04_09_00 contains updates to allow for test beam reconstruction in the presence of only two views and support for greater configurability in sliding cone mopup algorithms. This will not alter the products for any existing workflows.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by vitodb** [comment]
trigger build

**Comment by lgarren** [comment]
code-checks

**Comment by gartung** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Pull request merged**
