### PR TITLE
feature/larpandoracontent_v03_19_03

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR contains computational performance improvements related to the calculation of cluster spans. These improvements reduce reconstruction time in the ProtoDUNE-SP context by 25%, and 15% in the DUNEFD context by caching a cluster-related variable.

Please note this PR depends upon [changes](https://github.com/PandoraPFA/PandoraSDK/pull/13) to the Cluster class in the SDK (please see the associated email for further details).

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
I think I jumped the gun a little bit.  Chatting with Andy, these tests will most likely fail, due to the SDK changes being absent...

**Comment by lgarren** [comment]
trigger build

Not sure if this will work without pandora v03_16_00

**Comment by lgarren** [comment]
Oops, yes, the tests are going to fail once again.

**Comment by lgarren** [comment]
The unit tests are all good.  This will go in during the release process.

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
code-checks

**Pull request merged**
