### PR TITLE
Pandora deep learning infrastructure

### PR DESCRIPTION
**Pull request by AndyChappell**
This pull request introduces the infrastructure to support deep learning via LibTorch. There will be a talk on this and the associated larpandora pull request in the LArSoft Coordination meeting on 20 October.

A new library within the larpandoracontent product is introduced to support the deep learning features. This update introduces a dependency on the LibTorch ups product, though in keeping with previous Pandora pull requests, the product_deps file has not been updated (I can make such an addition if requested by the SciSoft team) and will be required for a successful default build.

CI testing was undertaken using a modified version of this branch that included the product_deps update, along with the associated larpandora branch, please see dune_ci/10372, which completed successfully.

Please feel free to contact me with any queries, or alternatively I'll be happy to address them in the LArSoft Coordination meeting.

### CODE REVIEW

**Comment by absolution1** [comment]
As an FYI, a larpandora PR (https://github.com/LArSoft/larpandora/pull/13) relies on this PR.  It would be good to advertise completion of the `product_deps` update in the larpandora PR as well as here.

**Comment by lgarren** [comment]
@AndyChappell, there seems to be some confusion.  We ask you not to change the release version in product_deps, but please go ahead and make any other necessary changes.  As discussed in https://cdcvs.fnal.gov/redmine/issues/24083, we expect the dependency to be modular and optional.

**Comment by lgarren** [comment]
I just tested the build.  It does not compile without libtorch.  As discussed, we cannot guarantee that libtorch is available for all compilers and platforms.  The code needs to build and work if libtorch is not available.

**Comment by lgarren** [comment]
Yes Andy, we need the build to proceed in automated fashion depending on whether or not libtorch is found.  This is done in larrecodnn if you need an example.

**Comment by AndyChappell** [comment]
Ok, thanks. I'll take a look and make the necessary changes (probably early next week at this stage), I may have some product_dep follow-up questions at some point as well.

**Comment by lgarren** [comment]
Happy to consult or provide suggestions.

**Comment by AndyChappell** [comment]
I've pushed updates to handle the presence/absence of LibTorch during the build ahead of any additional discussion in today's LArSoft Coordination Meeting.

**Comment by AndyChappell** [comment]
I've rebased the branch against the updates from the v03_21_01 patch, so from my perspective this should be ready to proceed. Thanks!

**Comment by lgarren** [comment]
approve

**Pull request merged**
