### PR TITLE
feature/larpandoracontent_v03 16 02

### PR DESCRIPTION
**Pull request by AndyChappell**
Hi, this PR includes a minor update to ensure LArContent builds with GCC 7.3. Versions of GCC prior to 8 that support C++ 17 issue warnings when there are unused structured bindings. This update avoids this problem. The details can be found in [PandoraPFA#126](https://github.com/PandoraPFA/LArContent/pull/126)

There are no behavioural changes as a result of this update and no experiment code/config changes are necessary.

We've triggered the CI off the relevant branches of the PandoraPFA/LArContent and dunetpc repositories. All tests passed, and the result can be found [here](https://dbweb5.fnal.gov:8443/LarCI/app/ns:DUNE/build_detail/phase_details?build_id=dune_ci/9420&platform=Linux%203.10.0-1127.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof).

Please do not hesitate to get in touch if further information is required.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by absolution1** [comment]
I had a look at the changes and they seem OK to me.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
