### PR TITLE
feature/larpandoracontent_v03_22_07

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR introduces new visualisation tools for MC particles and PFOs to provide more coherent and comprehensive information to aid assessment of reconstructed events. MC particles are presented with PDG information and matched between views, PFOs are presented with track/shower characterisation, are matched between views and can be linked to their best matched MC particle.

These changes will not alter product outputs for any experiment.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@AndyChappell  The build has failed with a sign-compare warning/error.  See the log in the github comments. I'm actually surprised to see this complaint from an e19 build.

**Comment by AndyChappell** [comment]
> @AndyChappell ... I'm actually surprised to see this complaint from an e19 build.

Me too, but I'll switch the type to address this and push an update later today.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests are normal.

**Comment by lgarren** [comment]
approve

**Comment by absolution1** [comment]
Does this one still need an L2 stamp?  It looks like it's been given such a stamp but I cannot find where...

**Comment by lgarren** [comment]
@absolution1 This one is good - thanks

**Pull request merged**
