### PR TITLE
feature/larpandoracontent_v03_22_10

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR contains a new algorithm that grows any shower particles to incorporate particles marked as being downstream (of the shower) in the particle hierarchy. The particle growing proceeds automatically, decoupling this algorithm from the precise logic used to form the hierarchy itself.

The algorithm is not yet active in any experimental configuration, and so no product changes are expected with this PR.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@AndyChappell  would you take a look at the CI tests?  In particular the uboone unit test has failed and it appears related to this PR.  Much thanks

**Comment by AndyChappell** [comment]
Hi @lgarren. It looks like the failure is linked to database access within CalibrationdEdX/pandoracali, so could this just be that the database was unavailable at this time and that a rerun may see the issue resolved? I don't see a path for this PR to produce downstream changes in pandoracali, as the new algorithm that forms the bulk of the PR isn't actually running yet.

**Comment by lgarren** [comment]
Thanks @AndyChappell   Will run the tests again.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The uboone unit test failure is consistent, but shows up when this PR is not included.

**Comment by lgarren** [comment]
approve

**Pull request merged**
