### PR TITLE
feature/larpandoracontent_v04_07_00

### PR DESCRIPTION
**Pull request by AndyChappell**
This PR for larpandoracontent v04_07_00 includes refactoring of a number of classes to support ongoing DUNE ND development efforts (no functionality is changed). There is also a fix for a bug in the way cluster contribution weights are calculated in the vertex refinement algorithm. This latter change is only relevant to SBND, where product changes are anticipated.

### CODE REVIEW

**Comment by AndyChappell** [comment]
> -code-checks Pull request failed...

Not sure what's going on with the code checks. Running format-code across all of these files indicates no changes are being made.

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@AndyChappell , we have an idea of what may be happening with the code checks.  Working to sort that out, but proceeding with the CI tests for this PR.

**Comment by knoepfel** [comment]
Some formatting changes were actually required based on https://github.com/LArSoft/larpandoracontent/blob/develop/.clang-format.  I've opened a new PR (#61) with those changes applied.

**Pull request closed without merging**
