### PR TITLE
feature/larpandoracontent_v04_00_00

### PR DESCRIPTION
**Pull request by AndyChappell**
v04_00_00 adds a new neutrino interaction vertex finding algorithm using a neural network-based approach.

A future release of dunereco will incorporate updates to the Pandora XML to make this new algorithm the default vertex finder for DUNEFD HD in the accelerator context, but for this update the algorithm is inactive and no product changes are expected.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Comment by henrylay97** [comment]
The SBND CI has flagged product changes in the pandora output as a result of this PR. As this PR is not meant to change anything I flagged this up with Andy. An example of the changes can be seen in [this log](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2022/07/12/stdout%23SYUR9NU.log) from the SBND particle gun tests.

It seems to be a result of [these lines](https://github.com/LArSoft/larpandoracontent/pull/44/files#diff-ddafbf2919975769238992a958764f8461d1147da3d3cad073f0a80071ad18cbL175-R178). @AndyChappell has a patch idea which we're testing now.

**Comment by AndyChappell** [comment]
> The SBND CI has flagged product changes...

The patch for this has now been applied and should eliminate the product differences seen. Thanks for flagging this @henrylay97 .

**Comment by lgarren** [comment]
trigger build

**Comment by henrylay97** [comment]
These SBND warnings are minor resource usage warnings, the product difference issue we saw earlier is indeed now gone.

**Pull request merged**
