### PR TITLE
Feature/larpandoracontent v03 23 02

### PR DESCRIPTION
**Pull request by henrylay97**
This PR provides a series of updates to the MVA vertex selection procedure. This includes:
- a fix to issue [#157](https://github.com/PandoraPFA/LArContent/issues/157)
- the addition of a new tool to calculate the dE/dx asymmetry around a vertex candidate
- the addition of a new variable related to the energy of the hits directly nearby a vertex candidate
- functionality for and inclusion of some "shared" variables between a pair of vertex candidates
- moving all four asymmetry type tools into an inheritance structure

It corresponds to PR [#169](https://github.com/PandoraPFA/LArContent/pull/169#event-4858313200) in the PandoraPFA/LArContent repository which has been approved and merged into this release branch. 

Due to this being a trained algorithm, legacy modes are provided for all changes and the default setup is to run in legacy mode. Hence, there should be no changes to any experiments' outputs until retraining is performed and the relevant xml changes are activated. Feel free to contact me for further information.

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
It looks like changes in dune and uboone have been occurring before the before.  SBND look OK!

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
code-checks

**Pull request merged**
