### PR TITLE
Feature/larpandoracontent v03 16 00

### PR DESCRIPTION
**Pull request by imawby**
Hello, this PR includes a set of features to improve the stitching of CR muon tracks across multiple LArTPCs and the reconstruction of highly transverse tracks via the use of hit width information. The PR breakdown is as follows: 
* Upgrades to the StitchingCosmicRayTool and the incorporation of hit width information in sliding linear fits #118 (PR)
* The development of the HitWidthClusterMerging algorithm #111 (PR) #117 (PR)
* Small tweaks to the HitWidthClusterMerging algorithm to catch exception code throws #119 (PR) 

With the application of this PR, the CR stitching improvements will be immediately activated in the CR reconstruction of all detectors. Once a related PR to dunetpc (https://cdcvs.fnal.gov/redmine/projects/dunetpc/repository?utf8=%E2%9C%93&rev=feature%2FIM_PandoraHitWidthAlgs) is passed through, the HitWidthClusterMerging will be in use in the neutrino and CR reconstruction chain of the DUNE FD and the CR reconstruction chain of ProtoDUNE-DP with a view to extend its use across more detectors in the future.

Details of these changes and their impacts on the reconstruction performance can be found in the following talks:
* Stitching Upgrades: https://indico.fnal.gov/event/43171/ (DUNEFD + ProtoDUNE-SP)
* HitWidthClusterMerging algorithm: https://indico.fnal.gov/event/43171/ (DUNEFD), https://indico.fnal.gov/event/24366/ (ProtoDUNE-DP) 

We've triggered the CI off the relevant branches of the PandoraPFA/LArContent and dunetpc repositories. The result, with 4 warnings related to changes in product sizes, which we expect given the changes in this PR, can be found here https://dbweb5.fnal.gov:8443/LarCI/app/ns:dune/build_detail/phase_details?build_id=dune_ci/9149&platform=Linux%203.10.0-1062.12.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof.

Please do not hesitate to get in touch if further information is required, i'm happy to help 😄

### CODE REVIEW

**Comment by lgarren** [comment]
@imawby  is a new build of pandora needed/requested to go along with this PR?  What tag?  We are currently using v03_11_01.

**Comment by lgarren** [comment]
It is confirmed that we do not need a new release of pandora.

**Comment by absolution1** [comment]
trigger build

**Comment by lgarren** [comment]
dunetpc has been successfully tested with this change, but the CI test for the other experiments has not been run.  I am taking care of that now and will report here.

**Comment by lgarren** [comment]
@absolution1 be aware that the DUNE CI tests will fail for the build you initiated.  However, dunetpc has already been tested successfully with feature/IM_PandoraHitWidthAlgs.

**Comment by absolution1** [comment]
I was mostly triggering for SBND but you said none of the other experiments are triggering right now?

**Comment by absolution1** [comment]
@lgarren the SBND tests look fine.
As a pandora developer, I'm not sure if it's appropriate for me to rubber stamp this PR in the LArSoft context, so I'll recuse myself from saying the magic trigger words.

**Comment by lgarren** [comment]
CI tests are normal.
https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/8599&builds=

**Comment by aihimmel** [comment]
If all the tests come back OK, and the developer is happy with the new features, I think this is ready to go. Approve

**Comment by chalt007** [comment]
I agree with Alex. Approving since all CI tests are OK.

**Comment by chalt007** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
