### PR TITLE
Feature/larpandoracontent v03 21 01

### PR DESCRIPTION
**Pull request by absolution1**
Hi everyone.

This PR is a patch release to fix a bug in `LArTrackShowerId/TrackShowerIdFeatureTool.cc` where a defence against accessing an empty container was missing.
Please see https://github.com/PandoraPFA/LArContent/pull/146 for more information if you're interested.

As an FYI, this PR is completely separate from the PyTorch-based PRs in the various pandora repos and there shouldn't be any problems if this PR is merged first.

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
It looks like the active CIs are returning unrelated warnings (I'll reach out to DUNE and SBND to update the reference files, I'm not sure who maintains the uboone CI).
The warnings appeared before the PR so I'm inclined to say that this PR hasn't made anything worse ;)

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
